version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: foremango_api
      MYSQL_USER: foremango_api
      MYSQL_PASSWORD: Kg44ve1e75v1Eq4V
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
